// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	lifecycle "source.quilibrium.com/quilibrium/monorepo/lifecycle"
)

// ComponentManagerBuilder is an autogenerated mock type for the ComponentManagerBuilder type
type ComponentManagerBuilder struct {
	mock.Mock
}

// AddWorker provides a mock function with given fields: _a0
func (_m *ComponentManagerBuilder) AddWorker(_a0 lifecycle.ComponentWorker) lifecycle.ComponentManagerBuilder {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for AddWorker")
	}

	var r0 lifecycle.ComponentManagerBuilder
	if rf, ok := ret.Get(0).(func(lifecycle.ComponentWorker) lifecycle.ComponentManagerBuilder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(lifecycle.ComponentManagerBuilder)
		}
	}

	return r0
}

// Build provides a mock function with no fields
func (_m *ComponentManagerBuilder) Build() *lifecycle.ComponentManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 *lifecycle.ComponentManager
	if rf, ok := ret.Get(0).(func() *lifecycle.ComponentManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lifecycle.ComponentManager)
		}
	}

	return r0
}

// NewComponentManagerBuilder creates a new instance of ComponentManagerBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewComponentManagerBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ComponentManagerBuilder {
	mock := &ComponentManagerBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
