// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// DynamicCommittee is an autogenerated mock type for the DynamicCommittee type
type DynamicCommittee struct {
	mock.Mock
}

// IdentitiesByRank provides a mock function with given fields: rank
func (_m *DynamicCommittee) IdentitiesByRank(rank uint64) ([]models.WeightedIdentity, error) {
	ret := _m.Called(rank)

	if len(ret) == 0 {
		panic("no return value specified for IdentitiesByRank")
	}

	var r0 []models.WeightedIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]models.WeightedIdentity, error)); ok {
		return rf(rank)
	}
	if rf, ok := ret.Get(0).(func(uint64) []models.WeightedIdentity); ok {
		r0 = rf(rank)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WeightedIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(rank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentitiesByState provides a mock function with given fields: stateID
func (_m *DynamicCommittee) IdentitiesByState(stateID models.Identity) ([]models.WeightedIdentity, error) {
	ret := _m.Called(stateID)

	if len(ret) == 0 {
		panic("no return value specified for IdentitiesByState")
	}

	var r0 []models.WeightedIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Identity) ([]models.WeightedIdentity, error)); ok {
		return rf(stateID)
	}
	if rf, ok := ret.Get(0).(func(models.Identity) []models.WeightedIdentity); ok {
		r0 = rf(stateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WeightedIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(models.Identity) error); ok {
		r1 = rf(stateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityByRank provides a mock function with given fields: rank, participantID
func (_m *DynamicCommittee) IdentityByRank(rank uint64, participantID models.Identity) (models.WeightedIdentity, error) {
	ret := _m.Called(rank, participantID)

	if len(ret) == 0 {
		panic("no return value specified for IdentityByRank")
	}

	var r0 models.WeightedIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, models.Identity) (models.WeightedIdentity, error)); ok {
		return rf(rank, participantID)
	}
	if rf, ok := ret.Get(0).(func(uint64, models.Identity) models.WeightedIdentity); ok {
		r0 = rf(rank, participantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.WeightedIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, models.Identity) error); ok {
		r1 = rf(rank, participantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityByState provides a mock function with given fields: stateID, participantID
func (_m *DynamicCommittee) IdentityByState(stateID models.Identity, participantID models.Identity) (models.WeightedIdentity, error) {
	ret := _m.Called(stateID, participantID)

	if len(ret) == 0 {
		panic("no return value specified for IdentityByState")
	}

	var r0 models.WeightedIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Identity, models.Identity) (models.WeightedIdentity, error)); ok {
		return rf(stateID, participantID)
	}
	if rf, ok := ret.Get(0).(func(models.Identity, models.Identity) models.WeightedIdentity); ok {
		r0 = rf(stateID, participantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.WeightedIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(models.Identity, models.Identity) error); ok {
		r1 = rf(stateID, participantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaderForRank provides a mock function with given fields: rank
func (_m *DynamicCommittee) LeaderForRank(rank uint64) (models.Identity, error) {
	ret := _m.Called(rank)

	if len(ret) == 0 {
		panic("no return value specified for LeaderForRank")
	}

	var r0 models.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (models.Identity, error)); ok {
		return rf(rank)
	}
	if rf, ok := ret.Get(0).(func(uint64) models.Identity); ok {
		r0 = rf(rank)
	} else {
		r0 = ret.Get(0).(models.Identity)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(rank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QuorumThresholdForRank provides a mock function with given fields: rank
func (_m *DynamicCommittee) QuorumThresholdForRank(rank uint64) (uint64, error) {
	ret := _m.Called(rank)

	if len(ret) == 0 {
		panic("no return value specified for QuorumThresholdForRank")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (uint64, error)); ok {
		return rf(rank)
	}
	if rf, ok := ret.Get(0).(func(uint64) uint64); ok {
		r0 = rf(rank)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(rank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Self provides a mock function with no fields
func (_m *DynamicCommittee) Self() models.Identity {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Self")
	}

	var r0 models.Identity
	if rf, ok := ret.Get(0).(func() models.Identity); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Identity)
	}

	return r0
}

// TimeoutThresholdForRank provides a mock function with given fields: rank
func (_m *DynamicCommittee) TimeoutThresholdForRank(rank uint64) (uint64, error) {
	ret := _m.Called(rank)

	if len(ret) == 0 {
		panic("no return value specified for TimeoutThresholdForRank")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (uint64, error)); ok {
		return rf(rank)
	}
	if rf, ok := ret.Get(0).(func(uint64) uint64); ok {
		r0 = rf(rank)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(rank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDynamicCommittee creates a new instance of DynamicCommittee. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDynamicCommittee(t interface {
	mock.TestingT
	Cleanup(func())
}) *DynamicCommittee {
	mock := &DynamicCommittee{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
