// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// EventLoop is an autogenerated mock type for the EventLoop type
type EventLoop[StateT models.Unique, VoteT models.Unique] struct {
	mock.Mock
}

// OnNewQuorumCertificateDiscovered provides a mock function with given fields: certificate
func (_m *EventLoop[StateT, VoteT]) OnNewQuorumCertificateDiscovered(certificate models.QuorumCertificate) {
	_m.Called(certificate)
}

// OnNewTimeoutCertificateDiscovered provides a mock function with given fields: certificate
func (_m *EventLoop[StateT, VoteT]) OnNewTimeoutCertificateDiscovered(certificate models.TimeoutCertificate) {
	_m.Called(certificate)
}

// OnPartialTimeoutCertificateCreated provides a mock function with given fields: rank, newestQC, lastRankTC
func (_m *EventLoop[StateT, VoteT]) OnPartialTimeoutCertificateCreated(rank uint64, newestQC models.QuorumCertificate, lastRankTC models.TimeoutCertificate) {
	_m.Called(rank, newestQC, lastRankTC)
}

// OnQuorumCertificateConstructedFromVotes provides a mock function with given fields: _a0
func (_m *EventLoop[StateT, VoteT]) OnQuorumCertificateConstructedFromVotes(_a0 models.QuorumCertificate) {
	_m.Called(_a0)
}

// OnTimeoutCertificateConstructedFromTimeouts provides a mock function with given fields: certificate
func (_m *EventLoop[StateT, VoteT]) OnTimeoutCertificateConstructedFromTimeouts(certificate models.TimeoutCertificate) {
	_m.Called(certificate)
}

// OnTimeoutProcessed provides a mock function with given fields: timeout
func (_m *EventLoop[StateT, VoteT]) OnTimeoutProcessed(timeout *models.TimeoutState[VoteT]) {
	_m.Called(timeout)
}

// OnVoteProcessed provides a mock function with given fields: vote
func (_m *EventLoop[StateT, VoteT]) OnVoteProcessed(vote *VoteT) {
	_m.Called(vote)
}

// SubmitProposal provides a mock function with given fields: proposal
func (_m *EventLoop[StateT, VoteT]) SubmitProposal(proposal *models.SignedProposal[StateT, VoteT]) {
	_m.Called(proposal)
}

// NewEventLoop creates a new instance of EventLoop. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventLoop[StateT models.Unique, VoteT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *EventLoop[StateT, VoteT] {
	mock := &EventLoop[StateT, VoteT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
