// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	consensus "source.quilibrium.com/quilibrium/monorepo/consensus"

	mock "github.com/stretchr/testify/mock"

	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"

	time "time"
)

// EventHandler is an autogenerated mock type for the EventHandler type
type EventHandler[StateT models.Unique, VoteT models.Unique] struct {
	mock.Mock
}

// OnLocalTimeout provides a mock function with no fields
func (_m *EventHandler[StateT, VoteT]) OnLocalTimeout() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OnLocalTimeout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnPartialTimeoutCertificateCreated provides a mock function with given fields: partialTimeoutCertificate
func (_m *EventHandler[StateT, VoteT]) OnPartialTimeoutCertificateCreated(partialTimeoutCertificate *consensus.PartialTimeoutCertificateCreated) error {
	ret := _m.Called(partialTimeoutCertificate)

	if len(ret) == 0 {
		panic("no return value specified for OnPartialTimeoutCertificateCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*consensus.PartialTimeoutCertificateCreated) error); ok {
		r0 = rf(partialTimeoutCertificate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnReceiveProposal provides a mock function with given fields: proposal
func (_m *EventHandler[StateT, VoteT]) OnReceiveProposal(proposal *models.SignedProposal[StateT, VoteT]) error {
	ret := _m.Called(proposal)

	if len(ret) == 0 {
		panic("no return value specified for OnReceiveProposal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.SignedProposal[StateT, VoteT]) error); ok {
		r0 = rf(proposal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnReceiveQuorumCertificate provides a mock function with given fields: quorumCertificate
func (_m *EventHandler[StateT, VoteT]) OnReceiveQuorumCertificate(quorumCertificate models.QuorumCertificate) error {
	ret := _m.Called(quorumCertificate)

	if len(ret) == 0 {
		panic("no return value specified for OnReceiveQuorumCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.QuorumCertificate) error); ok {
		r0 = rf(quorumCertificate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnReceiveTimeoutCertificate provides a mock function with given fields: timeoutCertificate
func (_m *EventHandler[StateT, VoteT]) OnReceiveTimeoutCertificate(timeoutCertificate models.TimeoutCertificate) error {
	ret := _m.Called(timeoutCertificate)

	if len(ret) == 0 {
		panic("no return value specified for OnReceiveTimeoutCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.TimeoutCertificate) error); ok {
		r0 = rf(timeoutCertificate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields: ctx
func (_m *EventHandler[StateT, VoteT]) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TimeoutChannel provides a mock function with no fields
func (_m *EventHandler[StateT, VoteT]) TimeoutChannel() <-chan time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TimeoutChannel")
	}

	var r0 <-chan time.Time
	if rf, ok := ret.Get(0).(func() <-chan time.Time); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time)
		}
	}

	return r0
}

// NewEventHandler creates a new instance of EventHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventHandler[StateT models.Unique, VoteT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *EventHandler[StateT, VoteT] {
	mock := &EventHandler[StateT, VoteT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
