// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// FinalizationConsumer is an autogenerated mock type for the FinalizationConsumer type
type FinalizationConsumer[StateT models.Unique] struct {
	mock.Mock
}

// OnFinalizedState provides a mock function with given fields: _a0
func (_m *FinalizationConsumer[StateT]) OnFinalizedState(_a0 *models.State[StateT]) {
	_m.Called(_a0)
}

// OnStateIncorporated provides a mock function with given fields: _a0
func (_m *FinalizationConsumer[StateT]) OnStateIncorporated(_a0 *models.State[StateT]) {
	_m.Called(_a0)
}

// NewFinalizationConsumer creates a new instance of FinalizationConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinalizationConsumer[StateT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *FinalizationConsumer[StateT] {
	mock := &FinalizationConsumer[StateT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
