// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// FollowerLoop is an autogenerated mock type for the FollowerLoop type
type FollowerLoop[StateT models.Unique, VoteT models.Unique] struct {
	mock.Mock
}

// AddCertifiedState provides a mock function with given fields: certifiedState
func (_m *FollowerLoop[StateT, VoteT]) AddCertifiedState(certifiedState *models.CertifiedState[StateT]) {
	_m.Called(certifiedState)
}

// NewFollowerLoop creates a new instance of FollowerLoop. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFollowerLoop[StateT models.Unique, VoteT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *FollowerLoop[StateT, VoteT] {
	mock := &FollowerLoop[StateT, VoteT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
