// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// FollowerConsumer is an autogenerated mock type for the FollowerConsumer type
type FollowerConsumer[StateT models.Unique, VoteT models.Unique] struct {
	mock.Mock
}

// OnDoubleProposeDetected provides a mock function with given fields: _a0, _a1
func (_m *FollowerConsumer[StateT, VoteT]) OnDoubleProposeDetected(_a0 *models.State[StateT], _a1 *models.State[StateT]) {
	_m.Called(_a0, _a1)
}

// OnFinalizedState provides a mock function with given fields: _a0
func (_m *FollowerConsumer[StateT, VoteT]) OnFinalizedState(_a0 *models.State[StateT]) {
	_m.Called(_a0)
}

// OnInvalidStateDetected provides a mock function with given fields: err
func (_m *FollowerConsumer[StateT, VoteT]) OnInvalidStateDetected(err *models.InvalidProposalError[StateT, VoteT]) {
	_m.Called(err)
}

// OnStateIncorporated provides a mock function with given fields: _a0
func (_m *FollowerConsumer[StateT, VoteT]) OnStateIncorporated(_a0 *models.State[StateT]) {
	_m.Called(_a0)
}

// NewFollowerConsumer creates a new instance of FollowerConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFollowerConsumer[StateT models.Unique, VoteT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *FollowerConsumer[StateT, VoteT] {
	mock := &FollowerConsumer[StateT, VoteT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
