// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// LeaderProvider is an autogenerated mock type for the LeaderProvider type
type LeaderProvider[StateT models.Unique, PeerIDT models.Unique, CollectedT models.Unique] struct {
	mock.Mock
}

// GetNextLeaders provides a mock function with given fields: ctx, prior
func (_m *LeaderProvider[StateT, PeerIDT, CollectedT]) GetNextLeaders(ctx context.Context, prior *StateT) ([]PeerIDT, error) {
	ret := _m.Called(ctx, prior)

	if len(ret) == 0 {
		panic("no return value specified for GetNextLeaders")
	}

	var r0 []PeerIDT
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *StateT) ([]PeerIDT, error)); ok {
		return rf(ctx, prior)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *StateT) []PeerIDT); ok {
		r0 = rf(ctx, prior)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PeerIDT)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *StateT) error); ok {
		r1 = rf(ctx, prior)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProveNextState provides a mock function with given fields: ctx, filter, priorState
func (_m *LeaderProvider[StateT, PeerIDT, CollectedT]) ProveNextState(ctx context.Context, rank uint64, filter []byte, priorState models.Identity) (*StateT, error) {
	ret := _m.Called(ctx, rank, filter, priorState)

	if len(ret) == 0 {
		panic("no return value specified for ProveNextState")
	}

	var r0 *StateT
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, []byte, models.Identity) (*StateT, error)); ok {
		return rf(ctx, rank, filter, priorState)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, []byte, models.Identity) *StateT); ok {
		r0 = rf(ctx, rank, filter, priorState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StateT)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, []byte, models.Identity) error); ok {
		r1 = rf(ctx, rank, filter, priorState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLeaderProvider creates a new instance of LeaderProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaderProvider[StateT models.Unique, PeerIDT models.Unique, CollectedT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaderProvider[StateT, PeerIDT, CollectedT] {
	mock := &LeaderProvider[StateT, PeerIDT, CollectedT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
