// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"

	time "time"
)

// Pacemaker is an autogenerated mock type for the Pacemaker type
type Pacemaker struct {
	mock.Mock
}

// CurrentRank provides a mock function with no fields
func (_m *Pacemaker) CurrentRank() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentRank")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// LatestQuorumCertificate provides a mock function with no fields
func (_m *Pacemaker) LatestQuorumCertificate() models.QuorumCertificate {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LatestQuorumCertificate")
	}

	var r0 models.QuorumCertificate
	if rf, ok := ret.Get(0).(func() models.QuorumCertificate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.QuorumCertificate)
		}
	}

	return r0
}

// PriorRankTimeoutCertificate provides a mock function with no fields
func (_m *Pacemaker) PriorRankTimeoutCertificate() models.TimeoutCertificate {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PriorRankTimeoutCertificate")
	}

	var r0 models.TimeoutCertificate
	if rf, ok := ret.Get(0).(func() models.TimeoutCertificate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.TimeoutCertificate)
		}
	}

	return r0
}

// ReceiveQuorumCertificate provides a mock function with given fields: quorumCertificate
func (_m *Pacemaker) ReceiveQuorumCertificate(quorumCertificate models.QuorumCertificate) (*models.NextRank, error) {
	ret := _m.Called(quorumCertificate)

	if len(ret) == 0 {
		panic("no return value specified for ReceiveQuorumCertificate")
	}

	var r0 *models.NextRank
	var r1 error
	if rf, ok := ret.Get(0).(func(models.QuorumCertificate) (*models.NextRank, error)); ok {
		return rf(quorumCertificate)
	}
	if rf, ok := ret.Get(0).(func(models.QuorumCertificate) *models.NextRank); ok {
		r0 = rf(quorumCertificate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.NextRank)
		}
	}

	if rf, ok := ret.Get(1).(func(models.QuorumCertificate) error); ok {
		r1 = rf(quorumCertificate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReceiveTimeoutCertificate provides a mock function with given fields: timeoutCertificate
func (_m *Pacemaker) ReceiveTimeoutCertificate(timeoutCertificate models.TimeoutCertificate) (*models.NextRank, error) {
	ret := _m.Called(timeoutCertificate)

	if len(ret) == 0 {
		panic("no return value specified for ReceiveTimeoutCertificate")
	}

	var r0 *models.NextRank
	var r1 error
	if rf, ok := ret.Get(0).(func(models.TimeoutCertificate) (*models.NextRank, error)); ok {
		return rf(timeoutCertificate)
	}
	if rf, ok := ret.Get(0).(func(models.TimeoutCertificate) *models.NextRank); ok {
		r0 = rf(timeoutCertificate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.NextRank)
		}
	}

	if rf, ok := ret.Get(1).(func(models.TimeoutCertificate) error); ok {
		r1 = rf(timeoutCertificate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Start provides a mock function with given fields: ctx
func (_m *Pacemaker) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TargetPublicationTime provides a mock function with given fields: proposalRank, timeRankEntered, parentStateId
func (_m *Pacemaker) TargetPublicationTime(proposalRank uint64, timeRankEntered time.Time, parentStateId models.Identity) time.Time {
	ret := _m.Called(proposalRank, timeRankEntered, parentStateId)

	if len(ret) == 0 {
		panic("no return value specified for TargetPublicationTime")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(uint64, time.Time, models.Identity) time.Time); ok {
		r0 = rf(proposalRank, timeRankEntered, parentStateId)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// TimeoutCh provides a mock function with no fields
func (_m *Pacemaker) TimeoutCh() <-chan time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TimeoutCh")
	}

	var r0 <-chan time.Time
	if rf, ok := ret.Get(0).(func() <-chan time.Time); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time)
		}
	}

	return r0
}

// NewPacemaker creates a new instance of Pacemaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPacemaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Pacemaker {
	mock := &Pacemaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
