// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// ReadOnlyConsensusStore is an autogenerated mock type for the ReadOnlyConsensusStore type
type ReadOnlyConsensusStore[VoteT models.Unique] struct {
	mock.Mock
}

// GetConsensusState provides a mock function with no fields
func (_m *ReadOnlyConsensusStore[VoteT]) GetConsensusState() (*models.ConsensusState[VoteT], error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConsensusState")
	}

	var r0 *models.ConsensusState[VoteT]
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.ConsensusState[VoteT], error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.ConsensusState[VoteT]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ConsensusState[VoteT])
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLivenessState provides a mock function with no fields
func (_m *ReadOnlyConsensusStore[VoteT]) GetLivenessState() (*models.LivenessState, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLivenessState")
	}

	var r0 *models.LivenessState
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.LivenessState, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.LivenessState); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LivenessState)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReadOnlyConsensusStore creates a new instance of ReadOnlyConsensusStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReadOnlyConsensusStore[VoteT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *ReadOnlyConsensusStore[VoteT] {
	mock := &ReadOnlyConsensusStore[VoteT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
