// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// StateSignerDecoder is an autogenerated mock type for the StateSignerDecoder type
type StateSignerDecoder[StateT models.Unique] struct {
	mock.Mock
}

// DecodeSignerIDs provides a mock function with given fields: state
func (_m *StateSignerDecoder[StateT]) DecodeSignerIDs(state *models.State[StateT]) ([]models.WeightedIdentity, error) {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for DecodeSignerIDs")
	}

	var r0 []models.WeightedIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.State[StateT]) ([]models.WeightedIdentity, error)); ok {
		return rf(state)
	}
	if rf, ok := ret.Get(0).(func(*models.State[StateT]) []models.WeightedIdentity); ok {
		r0 = rf(state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WeightedIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.State[StateT]) error); ok {
		r1 = rf(state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStateSignerDecoder creates a new instance of StateSignerDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateSignerDecoder[StateT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *StateSignerDecoder[StateT] {
	mock := &StateSignerDecoder[StateT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
