// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	consensus "source.quilibrium.com/quilibrium/monorepo/consensus"

	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// TimeoutSignatureAggregator is an autogenerated mock type for the TimeoutSignatureAggregator type
type TimeoutSignatureAggregator struct {
	mock.Mock
}

// Aggregate provides a mock function with no fields
func (_m *TimeoutSignatureAggregator) Aggregate() ([]consensus.TimeoutSignerInfo, models.AggregatedSignature, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Aggregate")
	}

	var r0 []consensus.TimeoutSignerInfo
	var r1 models.AggregatedSignature
	var r2 error
	if rf, ok := ret.Get(0).(func() ([]consensus.TimeoutSignerInfo, models.AggregatedSignature, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []consensus.TimeoutSignerInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consensus.TimeoutSignerInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() models.AggregatedSignature); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(models.AggregatedSignature)
		}
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Rank provides a mock function with no fields
func (_m *TimeoutSignatureAggregator) Rank() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rank")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// TotalWeight provides a mock function with no fields
func (_m *TimeoutSignatureAggregator) TotalWeight() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TotalWeight")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// VerifyAndAdd provides a mock function with given fields: signerID, sig, newestQCRank
func (_m *TimeoutSignatureAggregator) VerifyAndAdd(signerID models.Identity, sig []byte, newestQCRank uint64) (uint64, error) {
	ret := _m.Called(signerID, sig, newestQCRank)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAndAdd")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Identity, []byte, uint64) (uint64, error)); ok {
		return rf(signerID, sig, newestQCRank)
	}
	if rf, ok := ret.Get(0).(func(models.Identity, []byte, uint64) uint64); ok {
		r0 = rf(signerID, sig, newestQCRank)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(models.Identity, []byte, uint64) error); ok {
		r1 = rf(signerID, sig, newestQCRank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTimeoutSignatureAggregator creates a new instance of TimeoutSignatureAggregator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimeoutSignatureAggregator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimeoutSignatureAggregator {
	mock := &TimeoutSignatureAggregator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
