// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// TimeoutCollector is an autogenerated mock type for the TimeoutCollector type
type TimeoutCollector[VoteT models.Unique] struct {
	mock.Mock
}

// AddTimeout provides a mock function with given fields: timeoutState
func (_m *TimeoutCollector[VoteT]) AddTimeout(timeoutState *models.TimeoutState[VoteT]) error {
	ret := _m.Called(timeoutState)

	if len(ret) == 0 {
		panic("no return value specified for AddTimeout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.TimeoutState[VoteT]) error); ok {
		r0 = rf(timeoutState)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rank provides a mock function with no fields
func (_m *TimeoutCollector[VoteT]) Rank() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rank")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// NewTimeoutCollector creates a new instance of TimeoutCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimeoutCollector[VoteT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *TimeoutCollector[VoteT] {
	mock := &TimeoutCollector[VoteT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
