// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	consensus "source.quilibrium.com/quilibrium/monorepo/consensus"

	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// TimeoutCollectors is an autogenerated mock type for the TimeoutCollectors type
type TimeoutCollectors[VoteT models.Unique] struct {
	mock.Mock
}

// GetOrCreateCollector provides a mock function with given fields: rank
func (_m *TimeoutCollectors[VoteT]) GetOrCreateCollector(rank uint64) (consensus.TimeoutCollector[VoteT], bool, error) {
	ret := _m.Called(rank)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateCollector")
	}

	var r0 consensus.TimeoutCollector[VoteT]
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(uint64) (consensus.TimeoutCollector[VoteT], bool, error)); ok {
		return rf(rank)
	}
	if rf, ok := ret.Get(0).(func(uint64) consensus.TimeoutCollector[VoteT]); ok {
		r0 = rf(rank)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(consensus.TimeoutCollector[VoteT])
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) bool); ok {
		r1 = rf(rank)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(uint64) error); ok {
		r2 = rf(rank)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PruneUpToRank provides a mock function with given fields: lowestRetainedRank
func (_m *TimeoutCollectors[VoteT]) PruneUpToRank(lowestRetainedRank uint64) {
	_m.Called(lowestRetainedRank)
}

// NewTimeoutCollectors creates a new instance of TimeoutCollectors. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimeoutCollectors[VoteT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *TimeoutCollectors[VoteT] {
	mock := &TimeoutCollectors[VoteT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
