// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TraceLogger is an autogenerated mock type for the TraceLogger type
type TraceLogger struct {
	mock.Mock
}

// Error provides a mock function with given fields: message, err
func (_m *TraceLogger) Error(message string, err error) {
	_m.Called(message, err)
}

// Trace provides a mock function with given fields: message
func (_m *TraceLogger) Trace(message string) {
	_m.Called(message)
}

// NewTraceLogger creates a new instance of TraceLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTraceLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *TraceLogger {
	mock := &TraceLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
