// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	consensus "source.quilibrium.com/quilibrium/monorepo/consensus"
	"source.quilibrium.com/quilibrium/monorepo/lifecycle"

	mock "github.com/stretchr/testify/mock"

	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// VoteCollectors is an autogenerated mock type for the VoteCollectors type
type VoteCollectors[StateT models.Unique, VoteT models.Unique] struct {
	mock.Mock
}

// Done provides a mock function with no fields
func (_m *VoteCollectors[StateT, VoteT]) Done() <-chan struct{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// GetOrCreateCollector provides a mock function with given fields: rank
func (_m *VoteCollectors[StateT, VoteT]) GetOrCreateCollector(rank uint64) (consensus.VoteCollector[StateT, VoteT], bool, error) {
	ret := _m.Called(rank)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateCollector")
	}

	var r0 consensus.VoteCollector[StateT, VoteT]
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(uint64) (consensus.VoteCollector[StateT, VoteT], bool, error)); ok {
		return rf(rank)
	}
	if rf, ok := ret.Get(0).(func(uint64) consensus.VoteCollector[StateT, VoteT]); ok {
		r0 = rf(rank)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(consensus.VoteCollector[StateT, VoteT])
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) bool); ok {
		r1 = rf(rank)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(uint64) error); ok {
		r2 = rf(rank)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PruneUpToRank provides a mock function with given fields: lowestRetainedRank
func (_m *VoteCollectors[StateT, VoteT]) PruneUpToRank(lowestRetainedRank uint64) {
	_m.Called(lowestRetainedRank)
}

// Ready provides a mock function with no fields
func (_m *VoteCollectors[StateT, VoteT]) Ready() <-chan struct{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// Start provides a mock function with given fields: ctx
func (_m *VoteCollectors[StateT, VoteT]) Start(ctx lifecycle.SignalerContext) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(lifecycle.SignalerContext) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVoteCollectors creates a new instance of VoteCollectors. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoteCollectors[StateT models.Unique, VoteT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *VoteCollectors[StateT, VoteT] {
	mock := &VoteCollectors[StateT, VoteT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
