// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	consensus "source.quilibrium.com/quilibrium/monorepo/consensus"

	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// VoteCollector is an autogenerated mock type for the VoteCollector type
type VoteCollector[StateT models.Unique, VoteT models.Unique] struct {
	mock.Mock
}

// AddVote provides a mock function with given fields: vote
func (_m *VoteCollector[StateT, VoteT]) AddVote(vote *VoteT) error {
	ret := _m.Called(vote)

	if len(ret) == 0 {
		panic("no return value specified for AddVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*VoteT) error); ok {
		r0 = rf(vote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessState provides a mock function with given fields: state
func (_m *VoteCollector[StateT, VoteT]) ProcessState(state *models.SignedProposal[StateT, VoteT]) error {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for ProcessState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.SignedProposal[StateT, VoteT]) error); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rank provides a mock function with no fields
func (_m *VoteCollector[StateT, VoteT]) Rank() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rank")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// RegisterVoteConsumer provides a mock function with given fields: consumer
func (_m *VoteCollector[StateT, VoteT]) RegisterVoteConsumer(consumer consensus.VoteConsumer[VoteT]) {
	_m.Called(consumer)
}

// Status provides a mock function with no fields
func (_m *VoteCollector[StateT, VoteT]) Status() consensus.VoteCollectorStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 consensus.VoteCollectorStatus
	if rf, ok := ret.Get(0).(func() consensus.VoteCollectorStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(consensus.VoteCollectorStatus)
	}

	return r0
}

// NewVoteCollector creates a new instance of VoteCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoteCollector[StateT models.Unique, VoteT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *VoteCollector[StateT, VoteT] {
	mock := &VoteCollector[StateT, VoteT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
