// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// VoteAggregator is an autogenerated mock type for the VoteAggregator type
type VoteAggregator[StateT models.Unique, VoteT models.Unique] struct {
	mock.Mock
}

// AddState provides a mock function with given fields: state
func (_m *VoteAggregator[StateT, VoteT]) AddState(state *models.SignedProposal[StateT, VoteT]) {
	_m.Called(state)
}

// AddVote provides a mock function with given fields: vote
func (_m *VoteAggregator[StateT, VoteT]) AddVote(vote *VoteT) {
	_m.Called(vote)
}

// InvalidState provides a mock function with given fields: state
func (_m *VoteAggregator[StateT, VoteT]) InvalidState(state *models.SignedProposal[StateT, VoteT]) error {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for InvalidState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.SignedProposal[StateT, VoteT]) error); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PruneUpToRank provides a mock function with given fields: rank
func (_m *VoteAggregator[StateT, VoteT]) PruneUpToRank(rank uint64) {
	_m.Called(rank)
}

// Start provides a mock function with given fields: ctx
func (_m *VoteAggregator[StateT, VoteT]) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVoteAggregator creates a new instance of VoteAggregator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoteAggregator[StateT models.Unique, VoteT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *VoteAggregator[StateT, VoteT] {
	mock := &VoteAggregator[StateT, VoteT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
