// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WeightProvider is an autogenerated mock type for the WeightProvider type
type WeightProvider struct {
	mock.Mock
}

// GetWeightForBitmask provides a mock function with given fields: filter, bitmask
func (_m *WeightProvider) GetWeightForBitmask(filter []byte, bitmask []byte) uint64 {
	ret := _m.Called(filter, bitmask)

	if len(ret) == 0 {
		panic("no return value specified for GetWeightForBitmask")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func([]byte, []byte) uint64); ok {
		r0 = rf(filter, bitmask)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// NewWeightProvider creates a new instance of WeightProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeightProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeightProvider {
	mock := &WeightProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
