//! Conversions between prost-generated protobuf types and the internal
//! canonical-bytes types in [`super::types`].
//!
//! Mirror of `node/execution/intrinsics/hypergraph/hypergraph_conversions.go`.
//!
//! Two shapes for each message:
//!
//! - `proto::hypergraph::*` — wire-format protobuf types generated by
//!   prost-build. These are what gets serialized over the wire using
//!   proto3 encoding (distinct from the Quilibrium "canonical bytes"
//!   format used for signatures and hashing).
//! - [`super::types::*`] — the internal Rust structs this module
//!   operates on. Identical field set, minus the Go-side service
//!   dependencies (InclusionProver, KeyManager, Signer, VerifiableEncryptor).
//!   Those are threaded through at the intrinsic-dispatch level instead
//!   of living on the struct.
//!
//! The Go converter also parses the verenc-proof list out of the `data`
//! field on `VertexAdd`. The Rust side offers
//! [`split_vertex_add_proof_chunks`] and [`pack_vertex_add_proof_chunks`]
//! which decode/encode the same u16-length-prefixed list format as
//! opaque byte slices. Turning those slices into real `VerEncProof`
//! objects is the intrinsic dispatcher's job — it owns the crypto
//! context and does not live here.

use super::canonical::AggregateSignature;
use super::types::{
    HyperedgeAdd, HyperedgeRemove, HypergraphConfiguration, HypergraphDeploy,
    HypergraphUpdate, VertexAdd, VertexRemove,
};
use quil_types::error::{QuilError, Result};
use quil_types::proto::{hypergraph as pb, keys as keys_pb};

// =====================================================================
// HypergraphConfiguration ↔ pb::HypergraphConfiguration
// =====================================================================

impl HypergraphConfiguration {
    /// Convert from prost proto. Returns `None` if `pb` is `None`,
    /// matching the Go `HypergraphConfigurationFromProtobuf` nil behaviour.
    pub fn from_proto(
        pb: Option<&pb::HypergraphConfiguration>,
    ) -> Option<Self> {
        pb.map(|p| Self {
            read_public_key: p.read_public_key.clone(),
            write_public_key: p.write_public_key.clone(),
            owner_public_key: p.owner_public_key.clone(),
        })
    }

    /// Convert to prost proto. Mirror of Go
    /// `HypergraphIntrinsicConfiguration::ToProtobuf`.
    pub fn to_proto(&self) -> pb::HypergraphConfiguration {
        pb::HypergraphConfiguration {
            read_public_key: self.read_public_key.clone(),
            write_public_key: self.write_public_key.clone(),
            owner_public_key: self.owner_public_key.clone(),
        }
    }
}

// =====================================================================
// HypergraphDeploy ↔ pb::HypergraphDeploy
// =====================================================================
//
// Go:  HypergraphDeployFromProtobuf → HypergraphDeployArguments
//      HypergraphDeployArguments.ToProtobuf → protobufs.HypergraphDeploy
//
// Go rejects zero-length rdf_schema on from-proto. We match that.

impl HypergraphDeploy {
    pub fn from_proto(pb: &pb::HypergraphDeploy) -> Result<Self> {
        if pb.rdf_schema.is_empty() {
            return Err(QuilError::InvalidArgument(
                "hypergraph deploy from protobuf: missing rdf schema".into(),
            ));
        }
        let config = HypergraphConfiguration::from_proto(pb.config.as_ref());
        Ok(Self {
            config,
            rdf_schema: pb.rdf_schema.clone(),
        })
    }

    pub fn to_proto(&self) -> pb::HypergraphDeploy {
        pb::HypergraphDeploy {
            config: self.config.as_ref().map(HypergraphConfiguration::to_proto),
            rdf_schema: self.rdf_schema.clone(),
        }
    }
}

// =====================================================================
// HypergraphUpdate ↔ pb::HypergraphUpdate
// =====================================================================
//
// Go: HypergraphUpdateFromProtobuf only converts config when `pb.Config != nil`.
// The aggregate signature round-trips through a small local helper because
// the canonical-bytes AggregateSignature in this crate is a separate type
// from the prost-generated Bls48581AggregateSignature — we don't want the
// intrinsic layer leaking the prost shape into hashing/signing.

impl HypergraphUpdate {
    pub fn from_proto(pb: &pb::HypergraphUpdate) -> Result<Self> {
        Ok(Self {
            config: HypergraphConfiguration::from_proto(pb.config.as_ref()),
            rdf_schema: pb.rdf_schema.clone(),
            public_key_signature_bls48581: pb
                .public_key_signature_bls48581
                .as_ref()
                .map(aggregate_sig_from_proto)
                .transpose()?,
        })
    }

    pub fn to_proto(&self) -> pb::HypergraphUpdate {
        pb::HypergraphUpdate {
            config: self.config.as_ref().map(HypergraphConfiguration::to_proto),
            rdf_schema: self.rdf_schema.clone(),
            public_key_signature_bls48581: self
                .public_key_signature_bls48581
                .as_ref()
                .map(aggregate_sig_to_proto),
        }
    }
}

/// Convert a prost `Bls48581AggregateSignature` into the in-crate
/// [`AggregateSignature`] canonical-bytes shape. This collapses the
/// nested `Bls48581g2PublicKey` into our own `Bls48581G2PublicKey`
/// type so that the canonical-bytes serializer doesn't need to reach
/// into prost-generated code.
pub fn aggregate_sig_from_proto(
    pb: &keys_pb::Bls48581AggregateSignature,
) -> Result<AggregateSignature> {
    use super::canonical::Bls48581G2PublicKey as OurPubKey;

    let public_key = pb
        .public_key
        .as_ref()
        .map(|pk| {
            if pk.key_value.len() != OurPubKey::KEY_VALUE_LEN {
                Err(QuilError::InvalidArgument(format!(
                    "aggregate sig: BLS G2 public key has {} bytes, expected {}",
                    pk.key_value.len(),
                    OurPubKey::KEY_VALUE_LEN
                )))
            } else {
                Ok(OurPubKey {
                    key_value: pk.key_value.clone(),
                })
            }
        })
        .transpose()?;

    Ok(AggregateSignature {
        signature: pb.signature.clone(),
        public_key,
        bitmask: pb.bitmask.clone(),
    })
}

/// Convert an in-crate [`AggregateSignature`] back to the prost shape.
pub fn aggregate_sig_to_proto(
    sig: &AggregateSignature,
) -> keys_pb::Bls48581AggregateSignature {
    keys_pb::Bls48581AggregateSignature {
        signature: sig.signature.clone(),
        public_key: sig.public_key.as_ref().map(|pk| {
            keys_pb::Bls48581g2PublicKey {
                key_value: pk.key_value.clone(),
            }
        }),
        bitmask: sig.bitmask.clone(),
    }
}

// =====================================================================
// VertexAdd ↔ pb::VertexAdd
// =====================================================================

impl VertexAdd {
    /// Mirror of Go `VertexAddFromProtobuf`, minus the verenc-proof
    /// decoding. The raw proof list bytes are left in place on `data`
    /// — callers that need the parsed `[VerEncProof]` can invoke
    /// [`split_vertex_add_proof_chunks`] separately and feed each
    /// chunk through their crypto context.
    pub fn from_proto(pb: &pb::VertexAdd) -> Self {
        Self {
            domain: pb.domain.clone(),
            data_address: pb.data_address.clone(),
            data: pb.data.clone(),
            signature: pb.signature.clone(),
        }
    }

    pub fn to_proto(&self) -> pb::VertexAdd {
        pb::VertexAdd {
            domain: self.domain.clone(),
            data_address: self.data_address.clone(),
            data: self.data.clone(),
            signature: self.signature.clone(),
        }
    }
}

/// Decode the u16-length-prefixed proof list stored in
/// `VertexAdd::data`. Mirror of Go `extractVertexAddProofFromBytes`
/// minus the `verenc.ProofFromBytes` step.
///
/// Wire format:
/// ```text
/// [u16 BE count]
///   for each proof:
///     [u16 BE proof_len] [proof_len bytes]
/// ```
///
/// Returns one owned `Vec<u8>` per proof. Empty proof list is
/// rejected exactly like the Go version.
pub fn split_vertex_add_proof_chunks(data: &[u8]) -> Result<Vec<Vec<u8>>> {
    // Go: `len(pbData) < 4` rejected. That's a pre-check for
    // u16 count + at least one u16 len. We match it.
    if data.len() < 4 {
        return Err(QuilError::InvalidArgument(
            "extract vertex add proof from bytes: invalid data size".into(),
        ));
    }

    let mut cursor = 0usize;
    let count = read_u16_be(data, &mut cursor)?;
    if count == 0 {
        return Err(QuilError::InvalidArgument(
            "extract vertex add proof from bytes: invalid data size: 0".into(),
        ));
    }

    let mut out = Vec::with_capacity(count as usize);
    for _ in 0..count {
        let size = read_u16_be(data, &mut cursor)?;
        if size == 0 {
            return Err(QuilError::InvalidArgument(
                "extract vertex add proof from bytes: invalid proof size".into(),
            ));
        }
        let size = size as usize;
        if cursor + size > data.len() {
            return Err(QuilError::InvalidArgument(
                "extract vertex add proof from bytes: truncated proof data".into(),
            ));
        }
        out.push(data[cursor..cursor + size].to_vec());
        cursor += size;
    }

    Ok(out)
}

/// Pack a list of proof chunks into the same u16-length-prefixed
/// wire format consumed by [`split_vertex_add_proof_chunks`]. Mirror
/// of the serialization loop inside Go `VertexAdd::ToProtobuf`.
///
/// Rejects an empty proof list (Go returns `no proofs` error) and
/// rejects any proof whose length doesn't fit in a u16 (the wire
/// format is fundamentally incapable of carrying them).
pub fn pack_vertex_add_proof_chunks(proofs: &[Vec<u8>]) -> Result<Vec<u8>> {
    if proofs.is_empty() {
        return Err(QuilError::InvalidArgument(
            "pack vertex add proofs: no proofs".into(),
        ));
    }
    if proofs.len() > u16::MAX as usize {
        return Err(QuilError::InvalidArgument(format!(
            "pack vertex add proofs: too many proofs ({} > {})",
            proofs.len(),
            u16::MAX
        )));
    }

    let mut out = Vec::new();
    out.extend_from_slice(&(proofs.len() as u16).to_be_bytes());
    for (i, p) in proofs.iter().enumerate() {
        if p.is_empty() {
            return Err(QuilError::InvalidArgument(format!(
                "pack vertex add proofs: empty proof at index {}",
                i
            )));
        }
        if p.len() > u16::MAX as usize {
            return Err(QuilError::InvalidArgument(format!(
                "pack vertex add proofs: proof at index {} too large ({} > {})",
                i,
                p.len(),
                u16::MAX
            )));
        }
        out.extend_from_slice(&(p.len() as u16).to_be_bytes());
        out.extend_from_slice(p);
    }
    Ok(out)
}

/// Read a big-endian u16 from `data[cursor..]` and advance cursor.
fn read_u16_be(data: &[u8], cursor: &mut usize) -> Result<u16> {
    if *cursor + 2 > data.len() {
        return Err(QuilError::InvalidArgument(
            "unexpected end of input reading u16".into(),
        ));
    }
    let v = u16::from_be_bytes([data[*cursor], data[*cursor + 1]]);
    *cursor += 2;
    Ok(v)
}

// =====================================================================
// VertexRemove ↔ pb::VertexRemove
// =====================================================================

impl VertexRemove {
    pub fn from_proto(pb: &pb::VertexRemove) -> Self {
        Self {
            domain: pb.domain.clone(),
            data_address: pb.data_address.clone(),
            signature: pb.signature.clone(),
        }
    }

    pub fn to_proto(&self) -> pb::VertexRemove {
        pb::VertexRemove {
            domain: self.domain.clone(),
            data_address: self.data_address.clone(),
            signature: self.signature.clone(),
        }
    }
}

// =====================================================================
// HyperedgeAdd / HyperedgeRemove ↔ pb variants
// =====================================================================
//
// Go also decodes `pb.Value` into a typed `hypergraph.Hyperedge` via
// `AtomFromBytes`. That decoder recursively validates nested tries and
// depends on lazy-tree integration we haven't ported yet. For the
// intrinsic dispatch port to compile and run signature checks, leaving
// `value` as opaque bytes is sufficient — the typed hyperedge decode
// can be layered on once the lazy tree integration lands (task #64).

impl HyperedgeAdd {
    pub fn from_proto(pb: &pb::HyperedgeAdd) -> Self {
        Self {
            domain: pb.domain.clone(),
            value: pb.value.clone(),
            signature: pb.signature.clone(),
        }
    }

    pub fn to_proto(&self) -> pb::HyperedgeAdd {
        pb::HyperedgeAdd {
            domain: self.domain.clone(),
            value: self.value.clone(),
            signature: self.signature.clone(),
        }
    }
}

impl HyperedgeRemove {
    pub fn from_proto(pb: &pb::HyperedgeRemove) -> Self {
        Self {
            domain: pb.domain.clone(),
            value: pb.value.clone(),
            signature: pb.signature.clone(),
        }
    }

    pub fn to_proto(&self) -> pb::HyperedgeRemove {
        pb::HyperedgeRemove {
            domain: self.domain.clone(),
            value: self.value.clone(),
            signature: self.signature.clone(),
        }
    }
}

// =====================================================================
// Tests
// =====================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use super::super::canonical::Bls48581G2PublicKey;

    // -----------------------------------------------------------------
    // HypergraphConfiguration proto round-trip
    // -----------------------------------------------------------------

    fn sample_pb_config() -> pb::HypergraphConfiguration {
        pb::HypergraphConfiguration {
            read_public_key: vec![0x11u8; 57],
            write_public_key: vec![0x22u8; 57],
            owner_public_key: vec![0x33u8; 585],
        }
    }

    #[test]
    fn config_from_proto_none_returns_none() {
        assert!(HypergraphConfiguration::from_proto(None).is_none());
    }

    #[test]
    fn config_from_proto_some_copies_fields() {
        let pb = sample_pb_config();
        let c = HypergraphConfiguration::from_proto(Some(&pb)).unwrap();
        assert_eq!(c.read_public_key, pb.read_public_key);
        assert_eq!(c.write_public_key, pb.write_public_key);
        assert_eq!(c.owner_public_key, pb.owner_public_key);
    }

    #[test]
    fn config_to_proto_round_trip_preserves_fields() {
        let pb = sample_pb_config();
        let c = HypergraphConfiguration::from_proto(Some(&pb)).unwrap();
        let back = c.to_proto();
        assert_eq!(back, pb);
    }

    #[test]
    fn config_to_from_canonical_bytes_matches_after_proto_trip() {
        // Going proto → Rust → canonical bytes → Rust must preserve
        // field contents across the whole chain.
        let pb = sample_pb_config();
        let c = HypergraphConfiguration::from_proto(Some(&pb)).unwrap();
        let bytes = c.to_canonical_bytes().unwrap();
        let c2 = HypergraphConfiguration::from_canonical_bytes(&bytes).unwrap();
        assert_eq!(c2, c);
    }

    // -----------------------------------------------------------------
    // HypergraphDeploy proto round-trip
    // -----------------------------------------------------------------

    #[test]
    fn deploy_from_proto_rejects_empty_schema() {
        let pb = pb::HypergraphDeploy {
            config: Some(sample_pb_config()),
            rdf_schema: Vec::new(),
        };
        assert!(HypergraphDeploy::from_proto(&pb).is_err());
    }

    #[test]
    fn deploy_from_proto_preserves_fields() {
        let pb = pb::HypergraphDeploy {
            config: Some(sample_pb_config()),
            rdf_schema: b"schema-bytes".to_vec(),
        };
        let d = HypergraphDeploy::from_proto(&pb).unwrap();
        assert!(d.config.is_some());
        assert_eq!(d.rdf_schema, b"schema-bytes");
    }

    #[test]
    fn deploy_to_proto_round_trip() {
        let pb = pb::HypergraphDeploy {
            config: Some(sample_pb_config()),
            rdf_schema: b"schema-bytes".to_vec(),
        };
        let d = HypergraphDeploy::from_proto(&pb).unwrap();
        let pb2 = d.to_proto();
        assert_eq!(pb2, pb);
    }

    #[test]
    fn deploy_allows_none_config_in_from_proto() {
        // Go explicitly allows pb.Config == nil and just propagates nil.
        let pb = pb::HypergraphDeploy {
            config: None,
            rdf_schema: b"schema-bytes".to_vec(),
        };
        let d = HypergraphDeploy::from_proto(&pb).unwrap();
        assert!(d.config.is_none());
    }

    // -----------------------------------------------------------------
    // HypergraphUpdate + aggregate sig proto round-trip
    // -----------------------------------------------------------------

    fn sample_pb_aggregate_sig() -> keys_pb::Bls48581AggregateSignature {
        keys_pb::Bls48581AggregateSignature {
            signature: vec![0xAAu8; 74],
            public_key: Some(keys_pb::Bls48581g2PublicKey {
                key_value: vec![0x77u8; Bls48581G2PublicKey::KEY_VALUE_LEN],
            }),
            bitmask: vec![0x01, 0x02],
        }
    }

    #[test]
    fn aggregate_sig_from_proto_ok_with_valid_pubkey() {
        let pb_sig = sample_pb_aggregate_sig();
        let s = aggregate_sig_from_proto(&pb_sig).unwrap();
        assert_eq!(s.signature, pb_sig.signature);
        assert_eq!(s.bitmask, pb_sig.bitmask);
        assert!(s.public_key.is_some());
    }

    #[test]
    fn aggregate_sig_from_proto_rejects_wrong_pubkey_size() {
        let mut pb_sig = sample_pb_aggregate_sig();
        pb_sig.public_key = Some(keys_pb::Bls48581g2PublicKey {
            key_value: vec![0u8; 10],
        });
        assert!(aggregate_sig_from_proto(&pb_sig).is_err());
    }

    #[test]
    fn aggregate_sig_from_proto_no_pubkey_returns_none_pubkey() {
        let mut pb_sig = sample_pb_aggregate_sig();
        pb_sig.public_key = None;
        let s = aggregate_sig_from_proto(&pb_sig).unwrap();
        assert!(s.public_key.is_none());
    }

    #[test]
    fn aggregate_sig_to_proto_round_trip() {
        let pb_sig = sample_pb_aggregate_sig();
        let s = aggregate_sig_from_proto(&pb_sig).unwrap();
        let back = aggregate_sig_to_proto(&s);
        assert_eq!(back, pb_sig);
    }

    #[test]
    fn update_from_proto_full() {
        let pb = pb::HypergraphUpdate {
            config: Some(sample_pb_config()),
            rdf_schema: b"new-schema".to_vec(),
            public_key_signature_bls48581: Some(sample_pb_aggregate_sig()),
        };
        let u = HypergraphUpdate::from_proto(&pb).unwrap();
        assert!(u.config.is_some());
        assert_eq!(u.rdf_schema, b"new-schema");
        assert!(u.public_key_signature_bls48581.is_some());
    }

    #[test]
    fn update_to_proto_round_trip() {
        let pb = pb::HypergraphUpdate {
            config: Some(sample_pb_config()),
            rdf_schema: b"new-schema".to_vec(),
            public_key_signature_bls48581: Some(sample_pb_aggregate_sig()),
        };
        let u = HypergraphUpdate::from_proto(&pb).unwrap();
        let pb2 = u.to_proto();
        assert_eq!(pb2, pb);
    }

    #[test]
    fn update_from_proto_schema_only() {
        let pb = pb::HypergraphUpdate {
            config: None,
            rdf_schema: b"schema".to_vec(),
            public_key_signature_bls48581: Some(sample_pb_aggregate_sig()),
        };
        let u = HypergraphUpdate::from_proto(&pb).unwrap();
        assert!(u.config.is_none());
    }

    // -----------------------------------------------------------------
    // VertexAdd ↔ proto round-trip + proof-chunk helpers
    // -----------------------------------------------------------------

    fn sample_pb_vertex_add() -> pb::VertexAdd {
        pb::VertexAdd {
            domain: vec![0xAAu8; 32],
            data_address: vec![0xBBu8; 32],
            data: b"opaque-data".to_vec(),
            signature: vec![0xCCu8; 114],
        }
    }

    #[test]
    fn vertex_add_from_proto_preserves_fields() {
        let pb = sample_pb_vertex_add();
        let v = VertexAdd::from_proto(&pb);
        assert_eq!(v.domain, pb.domain);
        assert_eq!(v.data_address, pb.data_address);
        assert_eq!(v.data, pb.data);
        assert_eq!(v.signature, pb.signature);
    }

    #[test]
    fn vertex_add_to_proto_round_trip() {
        let pb = sample_pb_vertex_add();
        let v = VertexAdd::from_proto(&pb);
        assert_eq!(v.to_proto(), pb);
    }

    #[test]
    fn pack_and_split_proof_chunks_round_trip() {
        let chunks: Vec<Vec<u8>> = vec![
            b"proof-1".to_vec(),
            b"second-proof".to_vec(),
            b"p3".to_vec(),
        ];
        let packed = pack_vertex_add_proof_chunks(&chunks).unwrap();
        let unpacked = split_vertex_add_proof_chunks(&packed).unwrap();
        assert_eq!(unpacked, chunks);
    }

    #[test]
    fn pack_proof_chunks_rejects_empty_list() {
        assert!(pack_vertex_add_proof_chunks(&[]).is_err());
    }

    #[test]
    fn pack_proof_chunks_rejects_empty_chunk() {
        let bad: Vec<Vec<u8>> = vec![b"ok".to_vec(), Vec::new()];
        assert!(pack_vertex_add_proof_chunks(&bad).is_err());
    }

    #[test]
    fn split_proof_chunks_rejects_too_short_buffer() {
        assert!(split_vertex_add_proof_chunks(&[0x00, 0x01]).is_err());
    }

    #[test]
    fn split_proof_chunks_rejects_zero_count() {
        // count = 0 + padding to clear the min-length check
        let buf = [0x00, 0x00, 0x00, 0x00];
        assert!(split_vertex_add_proof_chunks(&buf).is_err());
    }

    #[test]
    fn split_proof_chunks_rejects_zero_size_element() {
        // count = 1, proof_len = 0 → rejected
        let buf = [0x00, 0x01, 0x00, 0x00];
        assert!(split_vertex_add_proof_chunks(&buf).is_err());
    }

    #[test]
    fn split_proof_chunks_rejects_truncated_payload() {
        // count = 1, proof_len = 10, but only 3 bytes follow
        let buf = [0x00, 0x01, 0x00, 0x0a, 0x01, 0x02, 0x03];
        assert!(split_vertex_add_proof_chunks(&buf).is_err());
    }

    #[test]
    fn pack_then_split_single_proof() {
        let chunks: Vec<Vec<u8>> = vec![vec![0xDEu8; 100]];
        let packed = pack_vertex_add_proof_chunks(&chunks).unwrap();
        // 2 (count) + 2 (size) + 100 (data)
        assert_eq!(packed.len(), 104);
        let unpacked = split_vertex_add_proof_chunks(&packed).unwrap();
        assert_eq!(unpacked.len(), 1);
        assert_eq!(unpacked[0].len(), 100);
    }

    // -----------------------------------------------------------------
    // VertexRemove ↔ proto
    // -----------------------------------------------------------------

    #[test]
    fn vertex_remove_proto_round_trip() {
        let pb = pb::VertexRemove {
            domain: vec![0x11u8; 32],
            data_address: vec![0x22u8; 32],
            signature: vec![0x33u8; 114],
        };
        let v = VertexRemove::from_proto(&pb);
        assert_eq!(v.to_proto(), pb);
    }

    // -----------------------------------------------------------------
    // HyperedgeAdd / HyperedgeRemove ↔ proto
    // -----------------------------------------------------------------

    #[test]
    fn hyperedge_add_proto_round_trip() {
        let pb = pb::HyperedgeAdd {
            domain: vec![0xA1u8; 32],
            value: b"opaque-hyperedge-bytes".to_vec(),
            signature: vec![0xB1u8; 114],
        };
        let h = HyperedgeAdd::from_proto(&pb);
        assert_eq!(h.to_proto(), pb);
    }

    #[test]
    fn hyperedge_remove_proto_round_trip() {
        let pb = pb::HyperedgeRemove {
            domain: vec![0xA2u8; 32],
            value: b"opaque-hyperedge-bytes".to_vec(),
            signature: vec![0xB2u8; 114],
        };
        let h = HyperedgeRemove::from_proto(&pb);
        assert_eq!(h.to_proto(), pb);
    }

    // -----------------------------------------------------------------
    // End-to-end: proto → rust → canonical bytes → rust → proto
    // -----------------------------------------------------------------

    #[test]
    fn vertex_add_full_pipeline() {
        let pb = sample_pb_vertex_add();
        let v = VertexAdd::from_proto(&pb);
        let cb = v.to_canonical_bytes().unwrap();
        let v2 = VertexAdd::from_canonical_bytes(&cb).unwrap();
        let pb2 = v2.to_proto();
        assert_eq!(pb2, pb);
    }

    #[test]
    fn hypergraph_update_full_pipeline() {
        let pb = pb::HypergraphUpdate {
            config: Some(sample_pb_config()),
            rdf_schema: b"schema-x".to_vec(),
            public_key_signature_bls48581: Some(sample_pb_aggregate_sig()),
        };
        let u = HypergraphUpdate::from_proto(&pb).unwrap();
        let cb = u.to_canonical_bytes().unwrap();
        let u2 = HypergraphUpdate::from_canonical_bytes(&cb).unwrap();
        let pb2 = u2.to_proto();
        assert_eq!(pb2, pb);
    }
}
