// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: ferret_proxy.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FerretProxy_AliceProxy_FullMethodName = "/quilibrium.node.ferretproxy.pb.FerretProxy/AliceProxy"
	FerretProxy_BobProxy_FullMethodName   = "/quilibrium.node.ferretproxy.pb.FerretProxy/BobProxy"
)

// FerretProxyClient is the client API for FerretProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FerretProxyClient interface {
	// Alice-side: Create TCP connection to specified port and forward data
	// Alice receives gRPC stream and forwards to local TCP connection
	AliceProxy(ctx context.Context, opts ...grpc.CallOption) (FerretProxy_AliceProxyClient, error)
	// Bob-side: Create TCP listener and forward data to gRPC stream
	// Bob creates TCP listener and forwards data to/from gRPC stream
	BobProxy(ctx context.Context, opts ...grpc.CallOption) (FerretProxy_BobProxyClient, error)
}

type ferretProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewFerretProxyClient(cc grpc.ClientConnInterface) FerretProxyClient {
	return &ferretProxyClient{cc}
}

func (c *ferretProxyClient) AliceProxy(ctx context.Context, opts ...grpc.CallOption) (FerretProxy_AliceProxyClient, error) {
	stream, err := c.cc.NewStream(ctx, &FerretProxy_ServiceDesc.Streams[0], FerretProxy_AliceProxy_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &ferretProxyAliceProxyClient{stream}
	return x, nil
}

type FerretProxy_AliceProxyClient interface {
	Send(*ProxyData) error
	Recv() (*ProxyData, error)
	grpc.ClientStream
}

type ferretProxyAliceProxyClient struct {
	grpc.ClientStream
}

func (x *ferretProxyAliceProxyClient) Send(m *ProxyData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ferretProxyAliceProxyClient) Recv() (*ProxyData, error) {
	m := new(ProxyData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ferretProxyClient) BobProxy(ctx context.Context, opts ...grpc.CallOption) (FerretProxy_BobProxyClient, error) {
	stream, err := c.cc.NewStream(ctx, &FerretProxy_ServiceDesc.Streams[1], FerretProxy_BobProxy_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &ferretProxyBobProxyClient{stream}
	return x, nil
}

type FerretProxy_BobProxyClient interface {
	Send(*ProxyData) error
	Recv() (*ProxyData, error)
	grpc.ClientStream
}

type ferretProxyBobProxyClient struct {
	grpc.ClientStream
}

func (x *ferretProxyBobProxyClient) Send(m *ProxyData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ferretProxyBobProxyClient) Recv() (*ProxyData, error) {
	m := new(ProxyData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FerretProxyServer is the server API for FerretProxy service.
// All implementations must embed UnimplementedFerretProxyServer
// for forward compatibility
type FerretProxyServer interface {
	// Alice-side: Create TCP connection to specified port and forward data
	// Alice receives gRPC stream and forwards to local TCP connection
	AliceProxy(FerretProxy_AliceProxyServer) error
	// Bob-side: Create TCP listener and forward data to gRPC stream
	// Bob creates TCP listener and forwards data to/from gRPC stream
	BobProxy(FerretProxy_BobProxyServer) error
	mustEmbedUnimplementedFerretProxyServer()
}

// UnimplementedFerretProxyServer must be embedded to have forward compatible implementations.
type UnimplementedFerretProxyServer struct {
}

func (UnimplementedFerretProxyServer) AliceProxy(FerretProxy_AliceProxyServer) error {
	return status.Errorf(codes.Unimplemented, "method AliceProxy not implemented")
}
func (UnimplementedFerretProxyServer) BobProxy(FerretProxy_BobProxyServer) error {
	return status.Errorf(codes.Unimplemented, "method BobProxy not implemented")
}
func (UnimplementedFerretProxyServer) mustEmbedUnimplementedFerretProxyServer() {}

// UnsafeFerretProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FerretProxyServer will
// result in compilation errors.
type UnsafeFerretProxyServer interface {
	mustEmbedUnimplementedFerretProxyServer()
}

func RegisterFerretProxyServer(s grpc.ServiceRegistrar, srv FerretProxyServer) {
	s.RegisterService(&FerretProxy_ServiceDesc, srv)
}

func _FerretProxy_AliceProxy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FerretProxyServer).AliceProxy(&ferretProxyAliceProxyServer{stream})
}

type FerretProxy_AliceProxyServer interface {
	Send(*ProxyData) error
	Recv() (*ProxyData, error)
	grpc.ServerStream
}

type ferretProxyAliceProxyServer struct {
	grpc.ServerStream
}

func (x *ferretProxyAliceProxyServer) Send(m *ProxyData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ferretProxyAliceProxyServer) Recv() (*ProxyData, error) {
	m := new(ProxyData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FerretProxy_BobProxy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FerretProxyServer).BobProxy(&ferretProxyBobProxyServer{stream})
}

type FerretProxy_BobProxyServer interface {
	Send(*ProxyData) error
	Recv() (*ProxyData, error)
	grpc.ServerStream
}

type ferretProxyBobProxyServer struct {
	grpc.ServerStream
}

func (x *ferretProxyBobProxyServer) Send(m *ProxyData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ferretProxyBobProxyServer) Recv() (*ProxyData, error) {
	m := new(ProxyData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FerretProxy_ServiceDesc is the grpc.ServiceDesc for FerretProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FerretProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quilibrium.node.ferretproxy.pb.FerretProxy",
	HandlerType: (*FerretProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AliceProxy",
			Handler:       _FerretProxy_AliceProxy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "BobProxy",
			Handler:       _FerretProxy_BobProxy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ferret_proxy.proto",
}
