// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.29.3
// source: hypergraph.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HypergraphConfiguration defines the keys for a hypergraph instance
type HypergraphConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 57 bytes Ed448
	ReadPublicKey []byte `protobuf:"bytes,1,opt,name=read_public_key,json=readPublicKey,proto3" json:"read_public_key,omitempty"`
	// 57 bytes Ed448
	WritePublicKey []byte `protobuf:"bytes,2,opt,name=write_public_key,json=writePublicKey,proto3" json:"write_public_key,omitempty"`
	// 585 byte BLS48-581
	OwnerPublicKey []byte `protobuf:"bytes,3,opt,name=owner_public_key,json=ownerPublicKey,proto3" json:"owner_public_key,omitempty"`
}

func (x *HypergraphConfiguration) Reset() {
	*x = HypergraphConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypergraph_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HypergraphConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypergraphConfiguration) ProtoMessage() {}

func (x *HypergraphConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_hypergraph_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypergraphConfiguration.ProtoReflect.Descriptor instead.
func (*HypergraphConfiguration) Descriptor() ([]byte, []int) {
	return file_hypergraph_proto_rawDescGZIP(), []int{0}
}

func (x *HypergraphConfiguration) GetReadPublicKey() []byte {
	if x != nil {
		return x.ReadPublicKey
	}
	return nil
}

func (x *HypergraphConfiguration) GetWritePublicKey() []byte {
	if x != nil {
		return x.WritePublicKey
	}
	return nil
}

func (x *HypergraphConfiguration) GetOwnerPublicKey() []byte {
	if x != nil {
		return x.OwnerPublicKey
	}
	return nil
}

// HypergraphDeploy creates a new hypergraph instance
type HypergraphDeploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The hypergraph configuration
	Config *HypergraphConfiguration `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The raw RDF schema definition
	RdfSchema []byte `protobuf:"bytes,2,opt,name=rdf_schema,json=rdfSchema,proto3" json:"rdf_schema,omitempty"`
}

func (x *HypergraphDeploy) Reset() {
	*x = HypergraphDeploy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypergraph_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HypergraphDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypergraphDeploy) ProtoMessage() {}

func (x *HypergraphDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_hypergraph_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypergraphDeploy.ProtoReflect.Descriptor instead.
func (*HypergraphDeploy) Descriptor() ([]byte, []int) {
	return file_hypergraph_proto_rawDescGZIP(), []int{1}
}

func (x *HypergraphDeploy) GetConfig() *HypergraphConfiguration {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *HypergraphDeploy) GetRdfSchema() []byte {
	if x != nil {
		return x.RdfSchema
	}
	return nil
}

// HypergraphUpdate updates the configuration of a hypergraph instance
type HypergraphUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The updated configuration, omitted if no update
	Config *HypergraphConfiguration `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The raw RDF schema definition, omitted if no update
	RdfSchema []byte `protobuf:"bytes,2,opt,name=rdf_schema,json=rdfSchema,proto3" json:"rdf_schema,omitempty"`
	// Signature from the owner key
	PublicKeySignatureBls48581 *BLS48581AggregateSignature `protobuf:"bytes,3,opt,name=public_key_signature_bls48581,json=publicKeySignatureBls48581,proto3" json:"public_key_signature_bls48581,omitempty"`
}

func (x *HypergraphUpdate) Reset() {
	*x = HypergraphUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypergraph_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HypergraphUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypergraphUpdate) ProtoMessage() {}

func (x *HypergraphUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_hypergraph_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypergraphUpdate.ProtoReflect.Descriptor instead.
func (*HypergraphUpdate) Descriptor() ([]byte, []int) {
	return file_hypergraph_proto_rawDescGZIP(), []int{2}
}

func (x *HypergraphUpdate) GetConfig() *HypergraphConfiguration {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *HypergraphUpdate) GetRdfSchema() []byte {
	if x != nil {
		return x.RdfSchema
	}
	return nil
}

func (x *HypergraphUpdate) GetPublicKeySignatureBls48581() *BLS48581AggregateSignature {
	if x != nil {
		return x.PublicKeySignatureBls48581
	}
	return nil
}

// VertexAdd adds a new vertex to the hypergraph
type VertexAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 32 bytes
	Domain []byte `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// 32 bytes
	DataAddress []byte `protobuf:"bytes,2,opt,name=data_address,json=dataAddress,proto3" json:"data_address,omitempty"`
	// VectorCommitmentTree serialized
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Ed448 signature
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *VertexAdd) Reset() {
	*x = VertexAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypergraph_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VertexAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VertexAdd) ProtoMessage() {}

func (x *VertexAdd) ProtoReflect() protoreflect.Message {
	mi := &file_hypergraph_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VertexAdd.ProtoReflect.Descriptor instead.
func (*VertexAdd) Descriptor() ([]byte, []int) {
	return file_hypergraph_proto_rawDescGZIP(), []int{3}
}

func (x *VertexAdd) GetDomain() []byte {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *VertexAdd) GetDataAddress() []byte {
	if x != nil {
		return x.DataAddress
	}
	return nil
}

func (x *VertexAdd) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VertexAdd) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// VertexRemove removes a vertex from the hypergraph
type VertexRemove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 32 bytes
	Domain []byte `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// 32 bytes
	DataAddress []byte `protobuf:"bytes,2,opt,name=data_address,json=dataAddress,proto3" json:"data_address,omitempty"`
	// Ed448 signature
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *VertexRemove) Reset() {
	*x = VertexRemove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypergraph_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VertexRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VertexRemove) ProtoMessage() {}

func (x *VertexRemove) ProtoReflect() protoreflect.Message {
	mi := &file_hypergraph_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VertexRemove.ProtoReflect.Descriptor instead.
func (*VertexRemove) Descriptor() ([]byte, []int) {
	return file_hypergraph_proto_rawDescGZIP(), []int{4}
}

func (x *VertexRemove) GetDomain() []byte {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *VertexRemove) GetDataAddress() []byte {
	if x != nil {
		return x.DataAddress
	}
	return nil
}

func (x *VertexRemove) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// HyperedgeAdd adds a new hyperedge to the hypergraph
type HyperedgeAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 32 bytes
	Domain []byte `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// Hyperedge serialized
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Ed448 signature
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *HyperedgeAdd) Reset() {
	*x = HyperedgeAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypergraph_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HyperedgeAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HyperedgeAdd) ProtoMessage() {}

func (x *HyperedgeAdd) ProtoReflect() protoreflect.Message {
	mi := &file_hypergraph_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HyperedgeAdd.ProtoReflect.Descriptor instead.
func (*HyperedgeAdd) Descriptor() ([]byte, []int) {
	return file_hypergraph_proto_rawDescGZIP(), []int{5}
}

func (x *HyperedgeAdd) GetDomain() []byte {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *HyperedgeAdd) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *HyperedgeAdd) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// HyperedgeRemove removes a hyperedge from the hypergraph
type HyperedgeRemove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 32 bytes
	Domain []byte `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// Hyperedge serialized
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Ed448 signature
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *HyperedgeRemove) Reset() {
	*x = HyperedgeRemove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypergraph_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HyperedgeRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HyperedgeRemove) ProtoMessage() {}

func (x *HyperedgeRemove) ProtoReflect() protoreflect.Message {
	mi := &file_hypergraph_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HyperedgeRemove.ProtoReflect.Descriptor instead.
func (*HyperedgeRemove) Descriptor() ([]byte, []int) {
	return file_hypergraph_proto_rawDescGZIP(), []int{6}
}

func (x *HyperedgeRemove) GetDomain() []byte {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *HyperedgeRemove) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *HyperedgeRemove) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_hypergraph_proto protoreflect.FileDescriptor

var file_hypergraph_proto_rawDesc = []byte{
	0x0a, 0x10, 0x68, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1d, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x2e, 0x68, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x70,
	0x62, 0x1a, 0x0a, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01,
	0x0a, 0x17, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x61,
	0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0d, 0x72, 0x65, 0x61, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x12, 0x28, 0x0a, 0x10, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x10, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x81, 0x01, 0x0a, 0x10, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x4e, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x71, 0x75, 0x69,
	0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x68, 0x79, 0x70,
	0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x79, 0x70, 0x65, 0x72,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x64,
	0x66, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x72, 0x64, 0x66, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0xf9, 0x01, 0x0a, 0x10, 0x48, 0x79,
	0x70, 0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x4e,
	0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36,
	0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x68, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x70, 0x62, 0x2e, 0x48,
	0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x64, 0x66, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x72, 0x64, 0x66, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x76, 0x0a,
	0x1d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x62, 0x6c, 0x73, 0x34, 0x38, 0x35, 0x38, 0x31, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75,
	0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x42,
	0x4c, 0x53, 0x34, 0x38, 0x35, 0x38, 0x31, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x1a, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x6c, 0x73,
	0x34, 0x38, 0x35, 0x38, 0x31, 0x22, 0x78, 0x0a, 0x09, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x41,
	0x64, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22,
	0x67, 0x0a, 0x0c, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x64,
	0x61, 0x74, 0x61, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x5a, 0x0a, 0x0c, 0x48, 0x79, 0x70, 0x65,
	0x72, 0x65, 0x64, 0x67, 0x65, 0x41, 0x64, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x22, 0x5d, 0x0a, 0x0f, 0x48, 0x79, 0x70, 0x65, 0x72, 0x65, 0x64, 0x67,
	0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x71, 0x75,
	0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x75, 0x69,
	0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x72, 0x65, 0x70, 0x6f,
	0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hypergraph_proto_rawDescOnce sync.Once
	file_hypergraph_proto_rawDescData = file_hypergraph_proto_rawDesc
)

func file_hypergraph_proto_rawDescGZIP() []byte {
	file_hypergraph_proto_rawDescOnce.Do(func() {
		file_hypergraph_proto_rawDescData = protoimpl.X.CompressGZIP(file_hypergraph_proto_rawDescData)
	})
	return file_hypergraph_proto_rawDescData
}

var file_hypergraph_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hypergraph_proto_goTypes = []interface{}{
	(*HypergraphConfiguration)(nil),    // 0: quilibrium.node.hypergraph.pb.HypergraphConfiguration
	(*HypergraphDeploy)(nil),           // 1: quilibrium.node.hypergraph.pb.HypergraphDeploy
	(*HypergraphUpdate)(nil),           // 2: quilibrium.node.hypergraph.pb.HypergraphUpdate
	(*VertexAdd)(nil),                  // 3: quilibrium.node.hypergraph.pb.VertexAdd
	(*VertexRemove)(nil),               // 4: quilibrium.node.hypergraph.pb.VertexRemove
	(*HyperedgeAdd)(nil),               // 5: quilibrium.node.hypergraph.pb.HyperedgeAdd
	(*HyperedgeRemove)(nil),            // 6: quilibrium.node.hypergraph.pb.HyperedgeRemove
	(*BLS48581AggregateSignature)(nil), // 7: quilibrium.node.keys.pb.BLS48581AggregateSignature
}
var file_hypergraph_proto_depIdxs = []int32{
	0, // 0: quilibrium.node.hypergraph.pb.HypergraphDeploy.config:type_name -> quilibrium.node.hypergraph.pb.HypergraphConfiguration
	0, // 1: quilibrium.node.hypergraph.pb.HypergraphUpdate.config:type_name -> quilibrium.node.hypergraph.pb.HypergraphConfiguration
	7, // 2: quilibrium.node.hypergraph.pb.HypergraphUpdate.public_key_signature_bls48581:type_name -> quilibrium.node.keys.pb.BLS48581AggregateSignature
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hypergraph_proto_init() }
func file_hypergraph_proto_init() {
	if File_hypergraph_proto != nil {
		return
	}
	file_keys_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hypergraph_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HypergraphConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hypergraph_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HypergraphDeploy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hypergraph_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HypergraphUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hypergraph_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VertexAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hypergraph_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VertexRemove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hypergraph_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HyperedgeAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hypergraph_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HyperedgeRemove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hypergraph_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hypergraph_proto_goTypes,
		DependencyIndexes: file_hypergraph_proto_depIdxs,
		MessageInfos:      file_hypergraph_proto_msgTypes,
	}.Build()
	File_hypergraph_proto = out.File
	file_hypergraph_proto_rawDesc = nil
	file_hypergraph_proto_goTypes = nil
	file_hypergraph_proto_depIdxs = nil
}
